# Generated by Django 4.2.19 on 2025-02-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ManyToManyField(
                help_text="Select a language for this book", to="catalog.language"
            ),
        ),
    ]
