# Generated by Django 4.2.2 on 2025-02-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_book_language_book_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="birth"),
        ),
    ]
