# Generated by Django 4.2.2 on 2025-02-17 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
        migrations.RemoveConstraint(
            model_name="genre", name="genre_name_case_insensitive_unique",
        ),
        migrations.RemoveConstraint(
            model_name="language", name="language_name_case_insensitive_unique",
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Date of birth of the author",
                null=True,
                verbose_name="birth",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_death",
            field=models.DateField(
                blank=True,
                help_text="Date of death of the author",
                null=True,
                verbose_name="Died",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(
                help_text="First name of the author", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(help_text="Last name of the author", max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                help_text="Enter author of the book",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="catalog.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text='"13 Caracteres "             "<a href=https://www.isbn-international.org/content/what-isbn"             ">ISBN number</a>"',
                max_length=13,
                unique=True,
                verbose_name="ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(help_text="Enter title of the book", max_length=200),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="book",
            field=models.ForeignKey(
                help_text="Book",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="catalog.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="due_back",
            field=models.DateField(
                blank=True, help_text="Due date to return the book", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier of the book copy",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="imprint",
            field=models.CharField(help_text="Imprint of the book", max_length=200),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Maintenance"),
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="m",
                help_text="Availability of the book",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(help_text="Name of the genre", max_length=200),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(help_text="Name of the language", max_length=200),
        ),
        migrations.AddConstraint(
            model_name="genre",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="genre_name_case_insensitive_unique",
                violation_error_message="Genre already exists(case insensitive match)",
            ),
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="language_name_case_insensitive_unique",
                violation_error_message="Language already exists(case insensitive match)",
            ),
        ),
    ]
